var goods = [{
      url:'http://m.yixun.com/t/detail/index.html?pid=1283095&wxsg=1',
      cartUrl:'http://m.yixun.com/t/detail/index.html?pid=1283095&wxsg=1',
      title:'IBody Rainbow 蓝牙健康追踪器 黑色',
      promo:'酷炫设计只为你的健康',
      price:229,
      like:50,
      review:45,
      review1:30,
      review2:6,
      review3:9,
      pic:'img/1.jpg',
      qrcode:'img/1.png'
  },{
      url:'http://m.yixun.com/t/detail/index.html?pid=682349&wxsg=1',
      cartUrl:'http://m.yixun.com/t/detail/index.html?pid=682349&wxsg=1',
      title:'Boogie Board 液晶手写板 黑色',
      promo:'海外直购，前沿科技',
      price:299,
      like:32,
      review:21,
      review1:15,
      review2:1,
      review3:5,
      pic:'img/2.jpg',
      qrcode:'img/2.png'
  },{
      url:'http://m.yixun.com/t/detail/index.html?pid=1299565&wxsg=1',
      cartUrl:'http://m.yixun.com/t/detail/index.html?pid=1299565&wxsg=1',
      title:'美国进口 MISFIT SHINE 智能手环',
      promo:'是手环，更是奢华',
      price:889,
      like:245,
      review:0,
      review1:0,
      review2:0,
      review3:0,
      pic:'img/3.jpg',
      qrcode:'img/3.png'
  }];